"""
CrimePatrol Domain — Recommendation Entity
"""
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from uuid import UUID


class RecommendationCategory(str, Enum):
    PATROL = "patrol"
    INFRASTRUCTURE = "infrastructure"
    ALERT = "alert"
    TRAFFIC = "traffic"
    CCTV = "cctv"


class RecommendationPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class Recommendation:
    """
    A single actionable recommendation generated by the Recommendation Agent.
    Each recommendation has a priority score (1–100) and an estimated impact.
    """
    id: UUID
    prediction_id: UUID
    action: str                              # human-readable action
    category: RecommendationCategory
    priority: RecommendationPriority
    priority_score: int                      # 1–100 for sorting
    reason: str                              # why this is recommended
    estimated_impact: str                    # 'HIGH' | 'MEDIUM' | 'LOW'
    is_actioned: bool = False
    actioned_at: datetime | None = None
    created_at: datetime | None = None

    def __post_init__(self) -> None:
        if not (1 <= self.priority_score <= 100):
            raise ValueError(f"priority_score must be 1–100, got {self.priority_score}")
